<?php
$title = 'Add new star';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('star', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo "<br />";
echo $this->formRow($form->get('artist'));
echo "<br />";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
