<?php
$title = 'Star';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('star', array('action' => 'add')); ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $star) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($star->title); ?></td>
            <td><?php echo $this->escapeHtml($star->artist); ?></td>
            <td>
                <a href="<?php echo $this->url('star', array('action' => 'edit', 'id' => $star->id));
        ?>">Edit</a>
                <a href="<?php echo $this->url('star', array('action' => 'delete', 'id' => $star->id));
        ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
echo $this->paginationControl($this->paginator, 'sliding', array('partial/paginator.phtml', 'Star'), array('route' => 'star'));
?>